var mongoose = require('mongoose');

var schemaOptions = {
    timestamps: true,
    toJSON: {
        virtuals: true
    }
};

var robotSchema = new mongoose.Schema({
     _id: String,
     notes: String,
     category: String,
     mouth: String,
     nose: String,
     eyebrows: String,
     hair: String,
     ears: String,
     embodiment: String,
     lid: String,
     iris: String,
     wink: String,
     lips: String,
     tongue: String,
     year: Number,
     name: String,
     robot_type: String,
     full_head: String,
     screen_type: String,
     cheeks: String,
     physical_features: String,
     robot_height: String,
     face_color: String,
     face_turns_other_colors: String,
     face_gradient_to: String,
     face_shape: String,
     screen_size: String,
     head_motion: String,
     face_motion: String,
     info_display: String,
     blink_type: String,
     cheek_color: String,
     cheek_placement: String,
     cheek_shape: String,
     cheek_size: String,
     cheek_spacing: String,
     country: String,
     eye_color: String,
     eye_motion: String,
     eye_outline_color: String,
     eye_placement: String,
     eye_shape: String,
     eye_size: String,
     eye_spacing: String,
     eye_turns_other_colors_inside: String,
     eye_turns_other_shapes: String,
     eyebrow_arch: String,
     eyebrow_color: String,
     eyebrow_independent_motion: String,
     eyebrow_inner_edge_positions: String,
     eyebrow_length: String,
     eyebrow_motion: String,
     eyebrow_shape: String,
     glare_motion: String,
     hair_color: String,
     lash_shape: String,
     lashes_color: String,
     mouth_color: String,
     mouth_inside_color: String,
     mouth_length: String,
     mouth_motion: String,
     mouth_placement: String,
     mouth_shape: String,
     nose_3d: String,
     nose_color: String,
     nose_motion: String,
     nose_placement: String,
     nose_shape: String,
     nose_size: String,
     num_glare_circles: String,
     pupil: String,
     pupil_color: String,
     pupil_or_iris_motion: String,
     pupil_shapes: String,
     reflected_glare_color: String,
     teeth_shape: String
}, schemaOptions);

var Robot = mongoose.model('Robot', robotSchema);

module.exports = Robot;